//Bhavna
export const CREATE_USER = "CREATE_USER";
export const LOGIN = "LOGIN";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const SEND_OTP = "SEND_OTP";
export const VERIFY_OTP = "VERIFY_OTP";
export const ERROR_TYPE = "ERROR_TYPE";
export const GET_INDICES_BYID = "GET_INDICES_BYID";
export const OHLC_CHART_INDEX = "OHLC_CHART_INDEX";
export const GAINERS_LOSERS = "GAINERS_LOSERS";
export const OHLC_INDICES_DATA = "OHLC_INDICES_DATA";

//Aditya
export const GET_ALL_COMPANY = "GET_ALL_COMPANY";
export const GET_ALL_SECTORS = "GET_ALL_SECTORS";
export const GET_ALL_INDUSTRIES = "GET_ALL_INDUSTRIES";

//Piyush
export const ALL_NEWS = "ALL_NEWS";
export const NEWS_BY_ID = "NEWS_BY_ID";
export const GET_ALL_INDICES = "GET_ALL_INDICES";
export const LOADING_START = "LOADING_START";
export const LOADING_STOP = "LOADING_STOP";

//NIKHIL
export const COMPANY_DETAIL = "COMPANY_DETAIL";
export const COMPANY_DETAIL_BY_ID = "COMPANY_DETAIL_BY_ID";
export const BALANCE_SHEET = "BALANCE_SHEET";
export const CASH_FLOW = "CASH_FLOW";
export const PROFIT_AND_LOSS = "PROFIT_AND_LOSS";
export const OHLC_CHART = "OHLC_CHART";
export const GET_SIMILAR_TABLE = "OHLC_CHART";
export const GET_DROP_DOWN = "GET_DROP_DOWN";
export const GET_GAUGE_COMPANY1 = "GET_GAUGE_COMPANY1";
export const GET_GAUGE_COMPANY2 = "GET_GAUGE_COMPANY2";
export const MONTECARLO_COMPANY1 = "MONTECARLO_COMPANY1";
export const MONTECARLO_COMPANY2 = "MONTECARLO_COMPANY2";
export const ASSETS_COMPANY1 = "ASSETS_COMPANY1";
export const ASSETS_COMPANY2 = "ASSETS_COMPANY2";
export const VOLATILITY = "VOLATILITY";
export const SHARE_PRICE_COMPARISON = "SHARE_PRICE_COMPARISON";
export const SCREENER_SEARCH = "SCREENER_SEARCH"; //FOR SCREENER IN STOCKS LANDING PAGE

// Harshal
export const SEARCH_CONTENT = "SEARCH_CONTENT";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const COMPANY_DATES_BY_ID = "COMPANY_DATES_BY_ID";
